
title: Samantha Circeo
logo: /images/1circle.png
description: "Email: <a href='mailto:samantha.circeo@eastern.edu'>samantha.circeo@eastern.edu</a><br>
LinkedIn: <a href='https://www.linkedin.com/in/samantha-circeo-406b76123/'>samantha-circeo</a><br>
GitHub: <a href='https://github.com/samcirceo'>samcirceo</a>"
theme: jekyll-theme-minimal
favicon: /images/favicon.png
